* 기본 설정

In [15]:
import requests
import json
import pandas as pd

In [16]:
# 인증키
encodingKey = "e%2BhnMTtUR6KCEeT0JaUw91rq9kQKnCDlWy5kQug3YNpYGx0gHDpQN6dMtNV7IfFt9irWjAbV60gDoq827vCPgQ%3D%3D"
decodingKey = "e+hnMTtUR6KCEeT0JaUw91rq9kQKnCDlWy5kQug3YNpYGx0gHDpQN6dMtNV7IfFt9irWjAbV60gDoq827vCPgQ=="

* 공장

In [108]:
str = "# URL\nSeoulURL = \"http://api.odcloud.kr/api<iamURL>\"\nparams = {'serviceKey': decodingKey, 'pageNo': 1, 'numOfRows': 10, 'perPage': 1000}\n\nSeoulResponse = requests.get(SeoulURL, params=params)\nSeoulData = SeoulResponse.text\n\nSeoulJsonData = json.loads(SeoulData)\nSeoulDf = pd.json_normalize(SeoulJsonData['data'])\n\nSeoulDf.to_csv(\"Seoul.csv\", index=False, encoding='utf-8-sig')\nSeoulDf"

str = str.replace("Seoul", "years")
str = str.replace("<iamURL>", "/15083033/v1/uddi:ad52aabc-3723-428c-874b-90db571eeb6e")
print(str)

# URL
yearsURL = "http://api.odcloud.kr/api/15083033/v1/uddi:ad52aabc-3723-428c-874b-90db571eeb6e"
params = {'serviceKey': decodingKey, 'pageNo': 1, 'numOfRows': 10, 'perPage': 1000}

yearsResponse = requests.get(yearsURL, params=params)
yearsData = yearsResponse.text

yearsJsonData = json.loads(yearsData)
yearsDf = pd.json_normalize(yearsJsonData['data'])

yearsDf.to_csv("years.csv", index=False, encoding='utf-8-sig')
yearsDf

* 서울시

In [143]:
# URL
SeoulURL = "http://api.odcloud.kr/api/15083033/v1/uddi:324125cb-6185-41a8-9480-8be3a8e4a717"
params = {'serviceKey': decodingKey, 'pageNo': 1, 'numOfRows': 10, 'perPage': 334}

SeoulResponse = requests.get(SeoulURL, params=params)
SeoulData = SeoulResponse.text

SeoulJsonData = json.loads(SeoulData)
SeoulDf = pd.json_normalize(SeoulJsonData['data'])

# 유아교육과 학원 분류 생성
SeoulDf['분류'] = SeoulDf.apply(lambda x: '학원' if x['업종중분류']!='유아교육' else '유아교육', axis=1)
# 학원 분류일 때 앞에 붙는 '학원-' 삭제
SeoulDf['업종중분류'] = SeoulDf.apply(lambda x: x['업종중분류'][3:] 
                                     if x['분류']=='학원' else x['업종중분류'], axis=1)
SeoulDf['업종소분류'] = SeoulDf.apply(lambda x: x['업종소분류'][3:] 
                                     if x['분류']=='학원' else x['업종소분류'], axis=1)

# 컬럼명/순서 변경
SeoulDf.rename({'광역시도':'시도'}, axis=1, inplace=True)
SeoulDf = SeoulDf.reindex(['시도', '시군구', '업종대분류', '분류', '업종중분류', '업종소분류', '건수'], axis=1)

# CSV 저장
SeoulDf.to_csv("Seoul.csv", index=False, encoding='utf-8-sig')
SeoulDf

        시도  시군구  업종대분류  분류   업종중분류   업종소분류    건수
0    서울특별시  강남구  학문/교육  학원  보습교습입시    검정고시     2
1    서울특별시  강남구  학문/교육  학원      어학   어린이영어    18
2    서울특별시  강남구  학문/교육  학원      어학  외국어/어학   636
3    서울특별시  강남구  학문/교육  학원  보습교습입시      입시  1173
4    서울특별시  강남구  학문/교육  학원  보습교습입시      편입     3
..     ...  ...    ...  ..     ...     ...   ...
328  서울특별시  종로구  학문/교육  학원  음악미술무용      무용     5
329  서울특별시   중구  학문/교육  학원  예능취미체육      가요     3
330  서울특별시   중구  학문/교육  학원  음악미술무용      무용     5
331  서울특별시  중랑구  학문/교육  학원  음악미술무용      무용     2
332  서울특별시  중랑구  학문/교육  학원  예능취미체육  배우/탤런트     1

[333 rows x 7 columns]

* 상가업소 업력 현황 2018

In [105]:
# URL
density17URL = "http://api.odcloud.kr/api/15083033/v1/uddi:f17d71e8-5463-4f5b-9b8f-bc0f50ed66de"
params = {'serviceKey': decodingKey, 'pageNo': 1, 'numOfRows': 10, 'perPage': 10000}

density17Response = requests.get(density17URL, params=params)
density17Data = density17Response.text

density17JsonData = json.loads(density17Data)
density17Df = pd.json_normalize(density17JsonData['data'])

# density17Df.to_csv("density17.csv", index=False, encoding='utf-8-sig')
density17Df

     과밀지수(밀집도)     관리년월 대분류명           상권명칭  상권번호     중분류명
0       0.9847  2017-01   소매        인천종합터미널  1713   가전제품소매
1       1.6518  2017-01   소매   송우리시외버스터미널_2  2399   가전제품소매
2       0.4912  2017-01   소매           남선공원  1217   가전제품소매
3       1.7180  2017-01   소매  인천 연수구 연수2동_1  1683   가전제품소매
4       2.1680  2017-01   소매  부산 연제구 연산동역_4   439   가전제품소매
...        ...      ...  ...            ...   ...      ...
9995    3.1679  2017-01   소매   경북 구미시 진미동_2  1114  건강/미용식품
9996    0.7242  2017-01   소매  서울 금천구 시흥1동_4  1727  건강/미용식품
9997    1.3546  2017-01   소매    괴산시외버스공용터미널  1354  건강/미용식품
9998    0.6414  2017-01   소매       금남로4가역_4   357  건강/미용식품
9999    0.8021  2017-01   소매       시흥시립도서관앞  1600  건강/미용식품

[10000 rows x 6 columns]

* 상권별 업종 밀집 통계 2017

In [17]:
# URL
yearsURL = "http://api.odcloud.kr/api/15083033/v1/uddi:ad52aabc-3723-428c-874b-90db571eeb6e"
params = {'serviceKey': decodingKey, 'pageNo': 1, 'numOfRows': 10, 'perPage': 20625}

yearsResponse = requests.get(yearsURL, params=params)
yearsData = yearsResponse.text

yearsJsonData = json.loads(yearsData)
yearsDf = pd.json_normalize(yearsJsonData['data'])

# 학원 분류 추가
yearsDf['분류'] = yearsDf.apply(lambda x: '학원'
                                if "학원" in x['업종중분류'] else '기타', axis=1)
# 학원 분류일 때 앞에 붙는 '학원-' 삭제
yearsDf['업종중분류'] = yearsDf.apply(lambda x: x['업종중분류'][3:] 
                                     if x['분류']=='학원' and x['업종중분류']!='학원기타' 
                                     else (x['업종중분류'][2:] 
                                     if x['업종중분류']=='학원기타' 
                                     else x['업종중분류']), axis=1)

# 컬럼명/순서 변경
yearsDf.rename({'1년미만':'1년 미만'}, axis=1, inplace=True)
yearsDf.rename({'광역시도':'시도'}, axis=1, inplace=True)
yearsDf = yearsDf.reindex(['시도', '시군구', '업종대분류', '분류', '업종중분류',
                           '1년 미만', '1~2년', '2~3년', '3~5년', '5년 이상'], axis=1)

# 결측치 제거
yearsDf.dropna(inplace=True)

# float to int
yearsDf = yearsDf.astype({'1년 미만': int, '1~2년': int, '2~3년': int, '3~5년': int, '5년 이상': int})

# 합계 컬럼 생성
yearsDf['합계'] = yearsDf['1년 미만'] + yearsDf['1~2년'] + yearsDf['2~3년'] + yearsDf['3~5년'] + yearsDf['5년 이상']

# 평균 컬럼 생성
yearsDf['평균'] = ((0.5 * yearsDf['1년 미만']) + (1.5 * yearsDf['1~2년']) + 
                  (2.5 * yearsDf['2~3년']) + (4 * yearsDf['3~5년']) + (5 * yearsDf['5년 이상'])) / yearsDf['합계']
yearsDf['평균'] = round(yearsDf['평균'], 2)

yearsDf.to_csv("years.csv", index=False, encoding='utf-8-sig')
yearsDf

,시도,시군구,업종대분류,분류,업종중분류,1년 미만,1~2년,2~3년,3~5년,5년 이상,합계,평균
0,서울특별시,종로구,관광/여가/오락,기타,연극/영화/극장,1,2,42,39,16,100,3.44
1,서울특별시,종로구,관광/여가/오락,기타,전시/관람,0,6,18,35,44,103,4.02
2,서울특별시,종로구,관광/여가/오락,기타,PC/오락/당구/볼링등,0,5,12,86,20,123,3.91
3,서울특별시,종로구,관광/여가/오락,기타,경마/경륜/성인오락,0,1,1,1,2,5,3.60
4,서울특별시,종로구,관광/여가/오락,기타,스포츠/운동,0,0,1,0,0,1,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...
20620,제주특별자치도,서귀포시,학문/교육,학원,예능취미체육,5,1,1,0,22,29,4.02
20621,제주특별자치도,서귀포시,학문/교육,학원,보습교습입시,6,2,3,47,18,76,3.84
20622,제주특별자치도,서귀포시,학문/교육,학원,기타,8,1,17,53,28,107,3.74
20623,제주특별자치도,서귀포시,학문/교육,기타,유아교육,0,1,7,5,115,128,4.80
20624,제주특별자치도,서귀포시,학문/교육,기타,특수교육기관,0,1,0,0,3,4,4.12

In [34]:
# print("업종대분류: ", yearsDf['업종대분류'].unique())
# print("분류: ", yearsDf['분류'].unique())
# print(yearsDf.groupby('업종대분류')['업종중분류'].unique())

categoryDf = yearsDf.groupby('업종대분류')['업종중분류'].unique().to_frame().reset_index()

# categoryDf.to_csv("category.csv", index=False, encoding='utf-8-sig')


yearsDf[yearsDf['업종대분류'] == '학문/교육'].groupby('분류')['업종중분류'].unique()

분류
기타     [학교, 유아교육, 특수교육기관, 기타교육기관, 연구소, 도서관/독서실, 학문교육기타]
학원    [컴퓨터, 자격/국가고시, 창업취업취미, 기타, 예능취미체육, 음악미술무용, 어학,...
Name: 업종중분류, dtype: object

In [41]:
str = "[학교, 유아교육, 특수교육기관, 기타교육기관, 연구소, 도서관/독서실, 학문교육기타]"


str = str.replace("'", "\"").replace(" ", ", ").replace("[", "[\n\"업종중분류 선택\", ").replace("]", "\n]")
print(str)

AttributeError: 'list' object has no attribute 'replace'